Active=Active
Are\ you\ sure\ you\ want\ to\ delete\ this\ tag\ collection?=Are you sure you want to delete this tag collection?
Are\ you\ sure\ you\ want\ to\ delete\ this\ tag?=Are you sure you want to delete this tag?
Cancel=Cancel
Close=Close
create_tag_collection=Create Tag Collection
create_tag=Create Tag
creation_date=Creation Date
Download\ Templates=Download Templates
Download\ ToolTip=Download the Template .zip file in order to access sample templates for the Tag alert, along with a readme.txt file containing additional information.
delete_tag_collection=Delete Tag Collection
delete_tag=Delete Tag
description=Description
Dismissible=Dismissible
Distribution=Distribution
Edit=Edit
End\ Time=End Time
error_unique_externalsource=A collection can't have the same external source value than another existing collection.
error_unique_name=A collection can't have the same name than another existing collection.
external_modification=Maintained Externally
externalSourceName = External Source
externalSourceDescription = Ext. Source Description
externalid= External ID
From=From
Hosts=Hosts
invalid_time=Time was not valid
label=Label
manage_tags=Manage Tags
Message=Message
name=Name
Preview=Preview
previous=Previous
next=Next
Return=Return
save_tag_collection=Save Tag Collection
save_tag=Save Tag
Start\ Time=Start Time
Type=Type
tag=Tag
Tags=Tags
tagcollections=Tag Collections
tagcollection_created=Collection Created
tagcollection_deleted=Collection Deleted
delete_collection_confirmation=Are you sure you want to delete the collection "{name}"?
delete_tag_confirmation=Are you sure you want to delete the tag "{label}"?
tagcollection_updated=Tag Collection Updated
tagcollection=Collection
tagcollectionName=Tag Collection Name
tagservice-disabled=The Tag Service has not been enabled.  Set <tt>tagservice.enabled=true</tt> in your properties file to activate it.
tag_created=Tag Created
tag_deleted=Tag Deleted
tag_updated=Tag Updated
tag_label=Tag Label
tagsintagcollection=Tags in Tag Collection
Until=Until
uuid_missing=The requested record could not be found
site_collection=This is the collection of the site with id {0}, with tags used in the Assignments tool.
user_collection=This is your collection of tags, used in the Private Messages tool.
no_collections_found=No collections found
no_tags_in_collection=No tags are available in this collection

tag_label_required=The tag label is required
tag_label_too_long=The input for field tag label is too long
description_too_long=The input for field description is too long
external_id_too_long=The input for field external id is too long
contains_xss=The input contains content that violates the system security policy
actions=Actions
viewing_tag=Viewing tag: {label}
